name: 'Deploy Vercel Microservice'
description: 'Deploys a Vercel microservice if changes are detected in its directory.'
inputs:
  service_path:
    description: 'The path to the microservice directory (e.g., services/servico-usuarios)'
    required: true
  vercel_project_name:
    description: 'The Vercel project name for the microservice'
    required: true
  vercel_org_id:
    description: 'The Vercel Organization ID'
    required: true
  vercel_token:
    description: 'The Vercel API Token'
    required: true
outputs:
  url:
    description: 'The URL of the deployed microservice (if deployed)'
    value: ${{ steps.deploy.outputs.url || steps.get_current_url.outputs.url }}
  should_deploy:
    description: 'Whether the microservice was deployed (true) or not (false)'
    value: ${{ steps.check_changes.outputs.should_deploy }}
runs:
  using: 'composite'
  steps:
    - name: Check for file changes
      id: check_changes
      shell: bash
      run: |
        echo "Checking for changes in ${{ inputs.service_path }} between ${{ github.event.before }} and ${{ github.event.after }}"
        if git diff --quiet ${{ github.event.before }} ${{ github.event.after }} -- ${{ inputs.service_path }}; then
          echo "No changes detected in ${{ inputs.service_path }}."
          echo "should_deploy=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in ${{ inputs.service_path }}. Proceeding with deployment."
          echo "should_deploy=true" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Vercel on change
      id: deploy
      if: steps.check_changes.outputs.should_deploy == 'true'
      shell: bash
      run: |
        set -e
        set -o pipefail

        echo "Navigating to ${{ inputs.service_path }}"
        cd ${{ inputs.service_path }}

        echo "--- Linking Vercel Project ---"
        vercel link --project ${{ inputs.vercel_project_name }} --token ${{ inputs.vercel_token }} --scope ${{ inputs.vercel_org_id }} --yes
        echo "------------------------------"
        
        echo "--- Debugging Vercel CLI ---"
        which vercel || { echo "Error: Vercel CLI not found."; exit 1; }
        vercel --version || { echo "Error: Vercel CLI failed to get version."; exit 1; }
        vercel whoami --token ${{ inputs.vercel_token }} || { echo "Error: Vercel CLI failed to authenticate. Check VERCEL_TOKEN permissions."; exit 1; }
        echo "----------------------------"

        echo "Running Vercel deploy for ${{ inputs.vercel_project_name }}..."
        
        set +e
        DEPLOY_OUTPUT=$(vercel deploy --prod --token ${{ inputs.vercel_token }} --scope ${{ inputs.vercel_org_id }} 2>&1)
        DEPLOY_EXIT_CODE=$?
        set -e

        echo "$DEPLOY_OUTPUT"

        if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
          echo "Erro: O comando 'vercel deploy' falhou com código de saída $DEPLOY_EXIT_CODE."
          exit $DEPLOY_EXIT_CODE
        fi
        
        DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep "Production: " | awk '{print $2}')

        echo "--- Vercel Deploy Output (last line) ---"
        echo "$DEPLOY_URL"
        echo "---------------------------------"
        
        if [[ ! "$DEPLOY_URL" =~ ^https?://.*\.vercel\.app$ ]]; then
          echo "Erro: O comando 'vercel deploy' não retornou uma URL de deploy válida. Saída: $DEPLOY_URL"
          exit 1
        fi
        
        echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        echo "Deployed URL: $DEPLOY_URL"

    - name: Get Current Production URL if no changes
      id: get_current_url
      if: steps.check_changes.outputs.should_deploy == 'false'
      shell: bash
      run: |
        echo "Fetching current production URL for ${{ inputs.vercel_project_name }}"
        RAW_URL=$(vercel ls ${{ inputs.vercel_project_name }} --prod --token=${{ inputs.vercel_token }} --scope=${{ inputs.vercel_org_id }} | tail -n 1 | awk '{print $NF}')
        
        if [[ $RAW_URL == https://* ]]; then
          CURRENT_URL=$RAW_URL
        else
          CURRENT_URL="https://"$RAW_URL
        fi

        if [ -z "$CURRENT_URL" ] || [ "$CURRENT_URL" == "null" ]; then
          echo "Error: Could not fetch current production URL for ${{ inputs.vercel_project_name }}."
          exit 1
        fi
        echo "url=$CURRENT_URL" >> $GITHUB_OUTPUT
        echo "Current URL: $CURRENT_URL"
