name: Debug Vercel Variables

on:
  workflow_dispatch:

jobs:
  debug-vercel:
    runs-on: ubuntu-latest
    
    # O nome do ambiente que você criou nos segredos. 
    # Se for diferente de "production", por favor, altere aqui.
    environment: production

    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Check for VERCEL_TOKEN
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN secret is NOT available."
          else
            echo "VERCEL_TOKEN secret IS available."
          fi

      - name: Attempt to Authenticate with whoami
        run: vercel whoami --token=${{ secrets.VERCEL_TOKEN }}

      - name: Get Help for Redeploy Command
        run: vercel redeploy --help
