name: Trigger Vercel Consumers

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

env:
  AI_AGENT_CONSUMER_URL: https://servicoagentes-oegio2d3o-jeanmnorhens-projects.vercel.app/api/agents/consume
  SEARCH_CONSUMER_URL: https://servico-busca-knuwawj17-jeanmnorhens-projects.vercel.app/api/search/consume
  MONITORING_CONSUMER_URL: https://servico-monitoramento-qblwau6ia-jeanmnorhens-projects.vercel.app/api/monitoring/consume

jobs:
  trigger-consumers:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AI Agent Consumer
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" "$AI_AGENT_CONSUMER_URL"

      - name: Trigger Search Consumer
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" "$SEARCH_CONSUMER_URL"
          
      - name: Trigger Monitoring Consumer
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" "$MONITORING_CONSUMER_URL"
