name: Update Frontend Endpoints on Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'services/**'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  FRONTEND_PROJECT_NAME: 'frontend-tester'

jobs:
  update-and-redeploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Vercel CLI and jq
        run: |
          npm install -g vercel
          sudo apt-get update && sudo apt-get install -y jq

      - name: Identify Changed Backend Services
        id: changed_services
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Files changed in this push: $CHANGED_FILES"
          CHANGED_SERVICES=$(echo "$CHANGED_FILES" | grep 'services/' | awk -F'/' '{print $2}' | sort -u)
          if [ -z "$CHANGED_SERVICES" ]; then
            echo "No backend services were changed. Exiting."
            exit 0
          fi
          echo "Backend services changed: $CHANGED_SERVICES"
          echo "services=${CHANGED_SERVICES}" >> $GITHUB_OUTPUT

      - name: Update Vercel Environment Variables
        if: steps.changed_services.outputs.services
        run: |
          for SERVICE_DIR in ${{ steps.changed_services.outputs.services }}; do
            echo "Processing service: $SERVICE_DIR"
            VERCEL_PROJECT_NAME=$SERVICE_DIR
            ENV_VAR_NAME=""
            case $SERVICE_DIR in
              "servico-agentes-ia") ENV_VAR_NAME="NEXT_PUBLIC_AI_API_URL" ;;
              "servico-busca") ENV_VAR_NAME="NEXT_PUBLIC_SEARCH_API_URL" ;;
              "servico-healthcheck") continue ;;
              "servico-lojas") ENV_VAR_NAME="NEXT_PUBLIC_STORES_API_URL" ;;
              "servico-monitoramento") ENV_VAR_NAME="NEXT_PUBLIC_MONITORING_API_URL" ;;
              "servico-ofertas") ENV_VAR_NAME="NEXT_PUBLIC_OFFERS_API_URL" ;;
              "servico-produtos") ENV_VAR_NAME="NEXT_PUBLIC_PRODUCTS_API_URL" ;;
              "servico-usuarios") ENV_VAR_NAME="NEXT_PUBLIC_USERS_API_URL" ;;
              *) echo "Warning: No mapping for $SERVICE_DIR." && continue ;;
            esac
            
                        echo "Fetching URL for $VERCEL_PROJECT_NAME..."
                        echo "Waiting for deployment of $VERCEL_PROJECT_NAME to be ready..."
                        RETRY_COUNT=0
                        MAX_RETRIES=18 # 18 retries * 10 seconds = 3 minutes
                        NEW_URL=""
                        while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
                          DEPLOYMENT_LIST=$(vercel ls $VERCEL_PROJECT_NAME --prod --token=${{ secrets.VERCEL_TOKEN }})
                          LATEST_STATUS=$(echo "$DEPLOYMENT_LIST" | head -n 2 | tail -n 1 | sed 's/●//g' | grep -o 'Ready')
                          if [[ "$LATEST_STATUS" == "Ready" ]]; then
                            NEW_URL=$(echo "$DEPLOYMENT_LIST" | head -n 2 | tail -n 1 | awk '{print $2}')
                            break
                          fi
                          echo "DEBUG: DEPLOYMENT_LIST for $VERCEL_PROJECT_NAME:"
              echo "$DEPLOYMENT_LIST"
              echo "DEBUG: LATEST_STATUS extracted: '$LATEST_STATUS'"
              echo "Deployment for $VERCEL_PROJECT_NAME is in state '$LATEST_STATUS'. Waiting 10 seconds..."
                          sleep 10
                          RETRY_COUNT=$((RETRY_COUNT + 1))
                        done
            
                        if [[ -z "$NEW_URL" ]]; then
                          echo "Error: Could not get a ready deployment URL for $VERCEL_PROJECT_NAME in time."
                          continue
                        fi            
            echo "Found new URL: $NEW_URL"
            vercel env rm $ENV_VAR_NAME production -y --token=${{ secrets.VERCEL_TOKEN }} || true
            echo $NEW_URL | vercel env add $ENV_VAR_NAME production --token=${{ secrets.VERCEL_TOKEN }}
            echo "---"
          done

      - name: Trigger Redeployment of Frontend
        if: steps.changed_services.outputs.services
        run: |
          echo "Triggering a new production deployment for $FRONTEND_PROJECT_NAME..."
          echo "DEBUG: Fetching frontend deployment list..."
          FRONTEND_DEPLOYMENT_LIST=$(vercel ls $FRONTEND_PROJECT_NAME --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEBUG: FRONTEND_DEPLOYMENT_LIST:"
          echo "$FRONTEND_DEPLOYMENT_LIST"
          
          # Get the URL of the latest deployment with status 'Ready'
          FRONTEND_READY_LINE=$(echo "$FRONTEND_DEPLOYMENT_LIST" | grep 'Ready' | head -n 1)
          echo "DEBUG: FRONTEND_READY_LINE: '$FRONTEND_READY_LINE'"
          DEPLOYMENT_URL=$(echo "$FRONTEND_READY_LINE" | sed 's/●//g' | sed -n 's/.*\(https:\/\/[^ ]*\).*\/\1\/p')
          echo "DEBUG: DEPLOYMENT_URL extracted: '$DEPLOYMENT_URL'"

          if [[ -z "$DEPLOYMENT_URL" ]]; then
            echo "Error: Could not parse deployment URL for $FRONTEND_PROJECT_NAME to redeploy."
            exit 1
          fi

          echo "Redeploying production deployment: $DEPLOYMENT_URL"
          vercel redeploy $DEPLOYMENT_URL --target production --token=${{ secrets.VERCEL_TOKEN }}